version: "3.8"

services:
    postgres:
        image: postgres:latest
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=wenote
        volumes:
            - pg_data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: ["redis-server", "--appendonly", "yes"]

volumes:
    pg_data:
    redis_data:
